name: Build

on: 
  - push

jobs:
  #########################################################################################
  #############################        Rubocop       ######################################
  #########################################################################################
  rubocop:
    name: Rubocop Lint
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: rubocop
        run: echo Run rubocop
