name: Deploy Production

on:
  workflow_run:
    workflows: 
      - Build
    branches:
      - master
    types:
      - completed

  deploy_staging:
    name: Deploy staging
    runs-on: ubuntu-18.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: deploy
        run: echo Deploy
